let vehicles = [
 {id:'infiniti-qx56',make:'Infiniti',model:'QX56',year:2011,price:10500000,type:'SUV',condition:'Nigerian used',color:'Colour to confirm',paint:'#53585f',tag:'DISTRESS SALE',note:'Described as super clean in the listing. Ask Metro for current photos, inspection details and availability.'},
 {id:'hyundai-sonata',make:'Hyundai',model:'Sonata Sport',year:2016,price:12850000,type:'Sedan',condition:'Confirm condition',color:'Red',paint:'#923d43',tag:'SPORT SEDAN',note:'Red Sonata Sport. Confirm current condition, price and availability with Metro.'},
 {id:'toyota-rav4',make:'Toyota',model:'RAV4',year:2017,price:23800000,type:'SUV',condition:'Confirm condition',color:'White',paint:'#e3e3df',tag:'FAMILY SUV',note:'White Toyota RAV4. Ask Metro for current vehicle photos, condition and inspection arrangements.'},
 {id:'toyota-corolla',make:'Toyota',model:'Corolla',year:2012,price:6850000,type:'Sedan',condition:'Confirm condition',color:'Colour to confirm',paint:'#a0a3aa',tag:'EVERYDAY DRIVE',note:'Listed as South Africa spec. Confirm current condition, specification, price and availability.'},
 {id:'hyundai-santa-fe',make:'Hyundai',model:'Santa Fe Sport',year:2013,price:15650000,type:'SUV',condition:'Foreign used',color:'Colour to confirm',paint:'#5c6565',tag:'FOREIGN USED',note:'Listed as direct Belgium. Ask Metro to confirm the current vehicle details and inspection availability.'},
 {id:'xiaomi-su7',make:'Xiaomi',model:'SU7',year:null,price:78000000,type:'Sedan',condition:'Brand new',color:'Colour to confirm',paint:'#83938c',tag:'BRAND NEW',note:'Xiaomi SU7, listed as brand new. Confirm the model year, colour, specification and current availability.'}
];
const vehiclePhotos = {"toyota-rav4": ["assets/cars/toyota-rav4-1.jpg", "assets/cars/toyota-rav4-2.jpg"], "infiniti-qx56": ["assets/cars/infiniti-qx56-1.jpg", "assets/cars/infiniti-qx56-2.jpg"], "hyundai-sonata": ["assets/cars/hyundai-sonata-1.jpg", "assets/cars/hyundai-sonata-2.jpg"], "toyota-corolla": ["assets/cars/toyota-corolla-1.jpg", "assets/cars/toyota-corolla-2.jpg"], "xiaomi-su7": ["assets/cars/xiaomi-su7-1.jpg", "assets/cars/xiaomi-su7-2.jpg", "assets/cars/xiaomi-su7-3.jpg", "assets/cars/xiaomi-su7-4.jpg", "assets/cars/xiaomi-su7-5.jpg", "assets/cars/xiaomi-su7-6.jpg"], "hyundai-santa-fe": ["assets/cars/hyundai-santa-fe-1.jpg", "assets/cars/hyundai-santa-fe-2.jpg", "assets/cars/hyundai-santa-fe-3.jpg", "assets/cars/hyundai-santa-fe-4.jpg"]};
const photoLabels = {"toyota-rav4": ["Front view", "Rear view"], "infiniti-qx56": ["Front view", "Rear view"], "hyundai-sonata": ["Front view", "Rear view"], "toyota-corolla": ["Front view", "Rear view"], "xiaomi-su7": ["Front three-quarter view", "Front view", "Rear three-quarter view", "Rear view", "Dashboard and front seats", "Rear cabin and glass roof"], "hyundai-santa-fe": ["Front three-quarter view", "Rear three-quarter view", "Dashboard and front seats", "Rear seats and panoramic roof"]};
const instagramSources = {"infiniti-qx56": "https://www.instagram.com/p/DdE4IEpAKDJ/", "hyundai-sonata": "https://www.instagram.com/p/Dc89JjHgM_C/", "toyota-rav4": "https://www.instagram.com/p/DdE4OoqgD_v/", "toyota-corolla": "https://www.instagram.com/p/Dbn3epsAPS9/", "hyundai-santa-fe": "https://www.instagram.com/p/DblJeE4ALOq/", "xiaomi-su7": "https://www.instagram.com/p/Da0N-9MgMgq/"};
const $ = (s,r=document)=>r.querySelector(s);
const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
const money = n=>'₦'+n.toLocaleString('en-NG');
const title = v=>`${v.make} ${v.model}${v.year?' '+v.year:''}`;
let saved;
try {const raw=JSON.parse(localStorage.getItem('metro-saved')||'[]');saved=new Set(Array.isArray(raw)?raw.filter(id=>vehicles.some(v=>v.id===id)):[]);} catch {saved=new Set();}
let activeType='all', toastTimer;
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2500);}
function carArt(v){if(vehiclePhotos[v.id])return `<img class="vehicle-photo" src="${vehiclePhotos[v.id][0]}" alt="${title(v)} — front exterior" width="1152" height="1536" loading="lazy" decoding="async">`;const suv=v.type==='SUV';return `<svg class="car-art" viewBox="0 0 640 400" aria-hidden="true"><defs><linearGradient id="paint-${v.id}" x1="0" y1="0" x2="0.15" y2="1"><stop stop-color="#f3f3f0"/><stop offset=".27" stop-color="${v.paint}"/><stop offset=".8" stop-color="${v.paint}"/><stop offset="1" stop-color="#363940"/></linearGradient><linearGradient id="glass-${v.id}" x2=".5" y2="1"><stop stop-color="#626b73"/><stop offset="1" stop-color="#232831"/></linearGradient><radialGradient id="wheel-${v.id}"><stop stop-color="#868b91"/><stop offset=".22" stop-color="#dadbdc"/><stop offset=".27" stop-color="#373b42"/><stop offset=".68" stop-color="#676c74"/><stop offset=".74" stop-color="#171b22"/><stop offset="1" stop-color="#22262c"/></radialGradient></defs><ellipse cx="320" cy="300" rx="249" ry="15" fill="#24252a" opacity=".16"/><path d="${suv?'M73 250 85 207Q91 197 126 188L183 119Q195 105 218 106L420 110Q440 111 460 142L492 187 548 198Q568 203 572 225L574 271 546 288H87Q64 282 73 250Z':'M73 254 87 220Q92 210 159 196L222 142Q235 132 259 130L388 133Q414 135 450 175L475 196 544 209Q563 213 572 246L573 271 548 287H90Q65 280 73 254Z'}" fill="url(#paint-${v.id})" stroke="#31353c" stroke-width="2"/><path d="${suv?'M139 189 191 128Q199 119 217 119L413 122Q432 123 448 148L474 190Z':'M175 198 235 148Q242 143 260 143L385 146Q410 147 449 196Z'}" fill="url(#glass-${v.id})" stroke="#969ca3" stroke-width="2"/><path d="${suv?'M276 120 271 190M374 122 392 190':'M299 143 295 196M389 147 406 196'}" stroke="#313740" stroke-width="9"/><path d="M117 211Q319 198 525 215" fill="none" stroke="#fff" stroke-width="2" opacity=".55"/><path d="M214 200 209 266M379 200 390 267M220 273H382" fill="none" stroke="#343942" stroke-width="1.5" opacity=".7"/><path d="M85 225 125 219 131 233 83 238Z" fill="#f9f8df"/><path d="M538 220 562 228 565 241 539 237Z" fill="#c31834"/><path d="M88 260H120M508 263H560" stroke="#303740" stroke-width="6"/><rect x="232" y="216" width="23" height="4" rx="2" fill="#d1d3d6"/><rect x="402" y="217" width="23" height="4" rx="2" fill="#d1d3d6"/><path d="M191 187 177 179 159 183 160 197 185 198" fill="${v.paint}" stroke="#464c55"/><g fill="url(#wheel-${v.id})" stroke="#252b31" stroke-width="3"><circle cx="165" cy="271" r="43"/><circle cx="466" cy="271" r="43"/></g><g stroke="#bfc2c8" stroke-width="3" opacity=".7"><path d="M165 241v60M135 271h60M144 250l42 42M144 292l42-42M466 241v60M436 271h60M445 250l42 42M445 292l42-42"/></g><circle cx="165" cy="271" r="7" fill="#454b52"/><circle cx="466" cy="271" r="7" fill="#454b52"/></svg>`;}
function persistSaved(){try{localStorage.setItem('metro-saved',JSON.stringify([...saved]));}catch{}$('#savedCount').textContent=saved.size;$('#savedTabCount').textContent=saved.size;$('#shortlistButton').setAttribute('aria-label',`View ${saved.size} saved cars`);}
function getFiltered(){const search=$('#carSearch').value.trim().toLowerCase(),make=$('#makeFilter').value,budget=$('#budgetFilter').value,condition=$('#conditionFilter').value;let list=vehicles.filter(v=>(activeType==='all'||(activeType==='saved'?saved.has(v.id):v.type===activeType))&&(make==='all'||v.make===make)&&(budget==='all'||v.price<Number(budget))&&(condition==='all'||v.condition===condition)&&`${title(v)} ${v.type}`.toLowerCase().includes(search));const sort=$('#sortFilter').value;if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);if(sort==='year')list.sort((a,b)=>(b.year||0)-(a.year||0));return list;}
function render(){persistSaved();const list=getFiltered();$('#vehicleGrid').innerHTML=list.map(v=>`<article class="vehicle-card" data-id="${v.id}"><div class="vehicle-visual"><button class="card-open" data-detail="${v.id}" aria-label="View ${title(v)} details">${carArt(v)}<span class="vehicle-tag">${v.tag}</span><span class="photo-label">${vehiclePhotos[v.id]?`ACTUAL VEHICLE · ${vehiclePhotos[v.id].length} PHOTOS`:"ILLUSTRATION · VEHICLE PHOTO PENDING"}</span></button><button class="save-car" data-save="${v.id}" aria-pressed="${saved.has(v.id)}" aria-label="${saved.has(v.id)?'Unsave':'Save'} ${title(v)}">${saved.has(v.id)?'♥':'♡'}</button></div><div class="card-meta"><span>${v.year||'YEAR TO CONFIRM'} / ${v.type}</span><span>ABUJA</span></div><h3><a href="#${v.id}" data-detail="${v.id}">${v.make} ${v.model}</a></h3><p class="card-specs">${v.condition} · ${v.color}</p><div class="card-bottom"><div class="price">${money(v.price)}<small>Confirm availability</small></div><button class="card-enquire" data-enquire="${v.id}">Enquire <span>↗</span></button></div></article>`).join('');$('#resultCount').textContent=`${list.length} ${list.length===1?'car':'cars'} ${activeType==='saved'?'in your shortlist':'to explore'}`;$('#emptyState').hidden=list.length>0;if(window.metroCardsMotion)window.metroCardsMotion();}
function setTab(value){activeType=value;$$('[data-type]').forEach(b=>{b.classList.toggle('active',b.dataset.type===value);b.setAttribute('aria-pressed',String(b.dataset.type===value));});render();}
function reset(){for(const id of ['makeFilter','budgetFilter','conditionFilter'])$('#'+id).value='all';$('#sortFilter').value='featured';$('#carSearch').value='';setTab('all');}
for(const v of vehicles){const option=document.createElement('option');option.value=title(v);option.textContent=`${title(v)} — ${money(v.price)}`;$('#enquiryVehicle').append(option);}
$$('[data-type]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.type)));$('#carSearch').addEventListener('input',render);$$('.filters select').forEach(s=>s.addEventListener('change',render));$('#resetFilters').addEventListener('click',reset);$('#emptyReset').addEventListener('click',reset);$('#shortlistButton').addEventListener('click',()=>{setTab('saved');$('#inventory').scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth'});});
let dialogTrigger=null;
function openDialog(dialog,trigger=document.activeElement){dialogTrigger=trigger;dialog.showModal();document.body.style.overflow='hidden';}
function closeDialog(dialog){dialog.close();}
$$('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{document.body.style.overflow='';if(dialogTrigger?.isConnected)dialogTrigger.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog);}});$('[data-close]',dialog).addEventListener('click',()=>closeDialog(dialog));});
function detail(id,trigger){const v=vehicles.find(x=>x.id===id);if(!v)return;$('#vehicleDetails').innerHTML=`<div class="detail-art ${vehiclePhotos[v.id]?"detail-photos":""}">${vehiclePhotos[v.id]?vehiclePhotos[v.id].map((src,i)=>`<figure><img src="${src}" alt="${title(v)} — ${photoLabels[v.id][i]}" width="1152" height="1536" loading="lazy"><figcaption>${photoLabels[v.id][i]}</figcaption></figure>`).join(""):carArt(v)}</div><p class="eyebrow">${v.tag} · CONFIRM AVAILABILITY</p><h2 id="dialogTitle">${title(v)}</h2><p class="detail-price">${money(v.price)}</p><dl class="detail-specs"><div><dt>BODY STYLE</dt><dd>${v.type}</dd></div><div><dt>CONDITION</dt><dd>${v.condition}</dd></div><div><dt>COLOUR</dt><dd>${v.color}</dd></div><div><dt>ENQUIRIES</dt><dd>Abuja</dd></div></dl><p class="detail-note">${v.note} ${vehiclePhotos[v.id]?"Photos supplied by MetroCarDeals. Confirm current condition at inspection.":"Image is an illustration; request actual photos before deciding."}</p><a class="instagram-link detail-source" href="${instagramSources[v.id]}" target="_blank" rel="noopener noreferrer">View this car on Instagram ↗</a><a class="button button-wide whatsapp-cta detail-whatsapp" href="https://wa.me/2349030914429?text=${encodeURIComponent(`Hi Metro, I’m interested in the ${title(v)} listed at ${money(v.price)}. Is it available for an Abuja inspection?`)}" target="_blank" rel="noopener noreferrer">WhatsApp about this car <span>↗</span></a><button class="button button-wide" data-enquire="${v.id}">Enquire about this car <span>↗</span></button>`;openDialog($('#vehicleDialog'),trigger);}
function selectEnquiry(id){const v=vehicles.find(x=>x.id===id);if(!v)return;$('#enquiryVehicle').value=title(v);$('#enquiryMessage').value=`Hi Metro, I’m interested in the ${title(v)} listed at ${money(v.price)}. Is it still available? Please share current photos and inspection details.`;if($('#vehicleDialog').open)closeDialog($('#vehicleDialog'));$('#enquire').scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth'});setTimeout(()=>$('#enquiryName').focus({preventScroll:true}),reducedMotion.matches?0:450);}
document.addEventListener('click',e=>{const save=e.target.closest('[data-save]'),info=e.target.closest('[data-detail]'),enquire=e.target.closest('[data-enquire]');if(save){const id=save.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);const wasSaved=saved.has(id);render();const next=$(`[data-save="${id}"]`);if(next)next.focus({preventScroll:true});else $('#savedTab').focus({preventScroll:true});notify(wasSaved?'Added to your shortlist':'Removed from your shortlist');}if(info){e.preventDefault();detail(info.dataset.detail,info);}if(enquire)selectEnquiry(enquire.dataset.enquire);});
$('#enquiryForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#enquiryName').value.trim();if(!name){$('#enquiryName').setCustomValidity('Please enter your first name.');$('#enquiryName').reportValidity();return;}const choice=$('#enquiryVehicle').value;const message=`Hi Metro, I’m ${name}.\n\nInterested in: ${choice}\nMy area: ${$('#enquiryArea').value}\n\n${$('#enquiryMessage').value.trim()||'Please help me with the current options, prices and an Abuja inspection.'}\n\nSent from the MetroCarDeals showroom.`;$('#preparedMessage').value=message;$('#copyStatus').textContent='Nothing is sent until you tap Send in WhatsApp.';$('#openWhatsApp').href='https://wa.me/2349030914429?text='+encodeURIComponent(message);$('#alternateWhatsApp').href='https://wa.me/2349073965030?text='+encodeURIComponent(message);$('#copyEnquiry').innerHTML='Copy enquiry <span>⧉</span>';openDialog($('#enquiryDialog'));});$('#enquiryName').addEventListener('input',()=>$('#enquiryName').setCustomValidity(''));
$('#copyEnquiry').addEventListener('click',async()=>{const box=$('#preparedMessage');try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(box.value);$('#copyStatus').textContent='Copied. Your WhatsApp enquiry links are ready.';$('#copyEnquiry').innerHTML='Enquiry copied <span>✓</span>';}catch{box.focus();box.select();$('#copyStatus').textContent='Your message is selected. Use Copy on your device, then continue to WhatsApp.';}});
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const video=$('#heroVideo'),hero=$('.hero'),scenes=$$('[data-scene]');let playing=false,scheduled=false,targetTime=0,currentScene=-1;
function showScene(index){
 if(currentScene===index)return;
 currentScene=index;
 // Hide outgoing content immediately; animate only the incoming scene.
 scenes.forEach((scene,i)=>{
  const active=i===index;
  scene.hidden=!active;
  scene.inert=!active;
  scene.setAttribute('aria-hidden',String(!active));
  scene.classList.toggle('scene-active',active);
 });
 $('.glass-orbit').hidden=index===1;
}
function updateProgress(p){$('#angleLabel').textContent=`${String(Math.round(p*360)).padStart(3,'0')}°`;$('#filmProgress').style.width=`${p*100}%`;}
function seek(){if(!video.seeking&&video.readyState>=1&&Number.isFinite(targetTime)&&Math.abs(video.currentTime-targetTime)>.035)video.currentTime=targetTime;}
function updateScroll(){scheduled=false;if(playing||window.metroMotionActive)return;const r=hero.getBoundingClientRect();let p=Math.max(0,Math.min(1,-r.top/Math.max(1,hero.offsetHeight-$('.hero-stage').offsetHeight)));if(reducedMotion.matches)p=0;showScene(p<.35?0:p<.7?1:2);updateProgress(p);if(video.duration&&!reducedMotion.matches){targetTime=p*Math.max(0,video.duration-.06);if(!window.metroCanvasReady)seek();}}
window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateScroll);}}, {passive:true});window.addEventListener('resize',updateScroll);video.addEventListener('loadedmetadata',updateScroll);video.addEventListener('seeked',()=>{if(!playing&&!window.metroCanvasReady)seek();});
function stopFilm(){playing=false;$('#heroFrames').style.opacity=window.metroCanvasReady?'1':'0';video.pause();$('#playReveal').textContent='▶ Play film';$('#playReveal').setAttribute('aria-pressed','false');updateScroll();if(window.metroRefreshMotion)window.metroRefreshMotion();}
$('#playReveal').addEventListener('click',async()=>{if(playing){stopFilm();return;}try{playing=true;$('#heroFrames').style.opacity='0';video.currentTime=0;await video.play();$('#playReveal').textContent='Ⅱ Pause film';$('#playReveal').setAttribute('aria-pressed','true');showScene(0);}catch{playing=false;notify('The film could not play. Please try again.');}});video.addEventListener('ended',stopFilm);video.addEventListener('timeupdate',()=>{if(playing&&video.duration){const p=video.currentTime/video.duration;updateProgress(p);showScene(p<.35?0:p<.7?1:2);}});reducedMotion.addEventListener('change',()=>{stopFilm();updateScroll();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)stopFilm();});
$('#year').textContent=new Date().getFullYear();render();updateScroll();initMotion();
function initMotion(){
 if(!window.gsap||!window.ScrollTrigger||reducedMotion.matches)return;
 gsap.registerPlugin(ScrollTrigger);
 window.metroMotionActive=true;
 const canvas=$('#heroFrames'),ctx=canvas.getContext('2d',{alpha:false});
 const total=241,frames=new Array(total),head={progress:0};let rendered=-1,requested=0,loaded=0;
 function draw(){if(playing)return;const n=Math.min(total-1,Math.round(head.progress*(total-1)));requested=n;let image=frames[n];if(!image){for(let step=1;step<total;step++){if(frames[n-step]){image=frames[n-step];break;}if(frames[n+step]){image=frames[n+step];break;}}}if(!image)return;if(rendered===image.dataset.index)return;rendered=image.dataset.index;canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;ctx.drawImage(image,0,0);window.metroCanvasReady=true;canvas.style.opacity='1';}
 const queue=[0,60,120,180,240,...Array.from({length:total},(_,i)=>i).filter(i=>i%60!==0)];let cursor=0;
 async function loadNext(){if(cursor>=queue.length)return;const i=queue[cursor++],img=new Image();img.decoding='async';img.dataset.index=String(i);img.src=`assets/frames/${String(i+1).padStart(4,'0')}.webp`;try{await img.decode();frames[i]=img;loaded++;if(i===0||Math.abs(requested-i)<4)draw();}catch{}if(loaded===total)draw();loadNext();}
 for(let i=0;i<4;i++)loadNext();
 function motionUpdate(){if(playing)return;const p=head.progress;updateProgress(p);showScene(p<.35?0:p<.7?1:2);draw();if(!window.metroCanvasReady&&video.duration){targetTime=p*(video.duration-.06);seek();}}
 window.metroRefreshMotion=motionUpdate;
 const scroll=gsap.to(head,{progress:1,ease:'none',onUpdate:motionUpdate,scrollTrigger:{trigger:hero,start:()=>hero.offsetTop,end:()=>hero.offsetTop+hero.offsetHeight-$('.hero-stage').offsetHeight,scrub:.65,invalidateOnRefresh:true}});
 gsap.fromTo('.glass-orbit',{y:60,rotateY:-12,rotateX:6,opacity:.4},{y:-70,rotateY:9,rotateX:-3,opacity:1,ease:'none',scrollTrigger:{trigger:hero,start:()=>hero.offsetTop,end:()=>hero.offsetTop+hero.offsetHeight-$('.hero-stage').offsetHeight,scrub:1.1}});
 gsap.to('.glass-orbit',{x:25,ease:'none',scrollTrigger:{trigger:hero,start:()=>hero.offsetTop,end:()=>hero.offsetTop+hero.offsetHeight-$('.hero-stage').offsetHeight,scrub:1.4}});
 gsap.fromTo('.enquiry-form',{y:65,rotateX:5,opacity:.4},{y:0,rotateX:0,opacity:1,ease:'power2.out',scrollTrigger:{trigger:'.enquiry-form',start:'top 90%',end:'top 55%',scrub:.6}});
 let cardTriggers=[];
 window.metroCardsMotion=()=>{cardTriggers.forEach(t=>t.kill());cardTriggers=[];$$('.vehicle-card').forEach((card,i)=>{const anim=gsap.fromTo(card,{y:35,opacity:.4},{y:0,opacity:1,duration:.65,ease:'power2.out',scrollTrigger:{trigger:card,start:'top 97%',once:true}});cardTriggers.push(anim.scrollTrigger);});ScrollTrigger.refresh();};
 window.metroCardsMotion();
 if(matchMedia('(pointer:fine)').matches){$('#vehicleGrid').addEventListener('pointermove',e=>{const c=e.target.closest('.vehicle-visual');if(!c)return;const r=c.getBoundingClientRect();gsap.to(c,{rotateY:(e.clientX-r.left-r.width/2)/r.width*5,rotateX:-(e.clientY-r.top-r.height/2)/r.height*5,duration:.45,ease:'power2.out',transformPerspective:800});});$('#vehicleGrid').addEventListener('pointerleave',()=>gsap.to('.vehicle-visual',{rotateX:0,rotateY:0,duration:.5}));}
 reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches){ScrollTrigger.getAll().forEach(t=>t.kill());gsap.set(['.vehicle-card','.enquiry-form','.glass-orbit'],{clearProps:'all'});window.metroMotionActive=false;window.metroCanvasReady=false;canvas.style.opacity='0';updateScroll();}});
}

document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||e.defaultPrevented)return;const target=document.getElementById(a.hash.slice(1));if(target){e.preventDefault();target.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'start'});if(a.classList.contains('skip-link')){target.tabIndex=-1;target.focus({preventScroll:true});}}});
